### ISSUE TITLE
SQL query performance

### ISSUE THREAD

**Issue by tpluscode** [mchaloupka/DotNetR2RMLStore#8]
Hi

I've just tried to run some more complex queries and I'm concerned with the SQL produced.

First issue I see is that each property object map generates a unioned SELECT. Wouldn't it be possible to generate a single SQL SELECT and transform the columns into results accordingly?

Then the number of SELECTs seems to explode for each triple pattern in SPARQL. 

And lastly when I added a second triple pattern joined by a ref-object map the SQL literally explodes.  In my query I select the _main_ triples for a subject and the next level to include a blank node resulting from the second triple map. Normally I would use OPTIONAL though it's not yet implemented.

```
CONSTRUCT
{
  @subject ?p ?o .
  ?blank ?p2 ?o1 .
}
WHERE 
{ 
  @subject ?p ?o .
  @subject ?p1 ?blank . 
  ?blank ?p2 ?o1 .
}
```

Such query executed against r2rml with 2 triple maps each with 9 and 1 predicate object map respectively produces and SQL query already 4700 lines long. Add an rdf:type pattern and it's another 2500 lines more. With a more complex triple pattern I got a whopping 14k lines.

**Comment by mchaloupka** [comment]
Can you please provide the database schema and r2rml file?

**Comment by tpluscode** [comment]
[Here](https://github.com/wikibus/data.wikibus.org/tree/master/src/wikibus.tests/Scripts) are the scripts to initialize the datatbase. And [here](http://pastebin.com/JyBjEbbp) are the mappings. I have added some more maps since we last wrote.

**Comment by mchaloupka** [comment]
In the current version, I do not support custom SQL expression as logical table. I am not able to perform any optimizations upon them. I will support them in some later version. Maybe I will need to extend the mapping file a little bit. However, if you will use just tables directly, you will see that the performance is improved. Now, I will work on the support of other SPARQL queries than just basic triples.
